### ISSUE TITLE
fast-POST needs implementing

### ISSUE THREAD

**Issue by redbo** [troubling/hummingbird#11]
But I don't like the way fast-post is done in swift, and I propose we do it differently.

I don't like that a bunch of extra fields were crammed into created_at on the container database (3d time woooo).  Why didn't they add new fields to the container database to hold the new values?  That's first normal form.  It's what you learn the first day of database class.

Then I don't like that there can be multiple .meta files that have to be read in to serve a GET.  Or there can be multiple timestamps in a filename.  They're both canonical representations of the same data.  Who thought this was a good idea?  We should put everything into one data structure, and it should be forward-looking enough that a fancy V2 API with updatable metadata can use the same representation.

**Comment by clayg** [comment]
The biggest challenge was making a fast-POST not not revert the content-type set in a subsequent .meta back to the original content type in the .data

t0 PUT c-t:1
t1 POST c-t:2 o-m:a
t2 POST o-m:b

It seemed like the representation of the object should be:

t0 PUT c-t:2 o-m:b
instead of
t0 PUT c-t:1 o-m:b 

Obviously that's debatable - but seemed closest to how post-as-copy worked and a little easier for clients to reason about the expected behavior.

As far as the table schema, that was nothing more than expedience - I think it's pretty clearly tech debt - but at the time the volunteer contributor that was implementing the change didn't feel capable/comfortable/experienced with the on-demand change pattern and was more comfortable with the cram the data in the sqlite text field pattern (e.g. SLO bytes).  I'm sure in review/design it came up - but ultimately the implementation worked and got rid of slow-POST which was pretty big win so we swallowed the container schema.
